### ISSUE TITLE
Example in usage does not work

### ISSUE THREAD

**Issue by mikeparisstuff** [vilic/clime#30]
When I try to run the example in the usage section of the README, I get this error:

```
TypeError: Class constructor Command cannot be invoked without 'new'
    at new default_1 (/Users/michaelparis/Scaphold/code/fetch-schema/build/commands/default.js:8:42)
    at CLI.<anonymous> (/Users/michaelparis/Scaphold/code/fetch-schema/node_modules/clime/bld/core/cli.js:50:35)
    at next (native)
    at fulfilled (/Users/michaelparis/Scaphold/code/fetch-schema/node_modules/clime/bld/core/cli.js:4:58)
```

**Comment by vilic** [comment]
Hi, I just tested the usage case with both the 0.4 and 0.5 version of clime but got no error.

Can you provide detailed information like `tsconfig.json`, TypeScript version, Node.js version, Clime version?

**Comment by scallacs** [comment]
I had the same problem. I've added this options in my tsconfig.json to make it work

`
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
// ...
}
`

Would be nice to document it in the README.md

**Comment by vilic** [comment]
@scallacs Thanks, will update README.
